name: Snowflake Bundle

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-snowflake-bundle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Create virtual environment
      run: python -m venv venv

    - name: Install dependencies in venv
      run: |
        . venv/bin/activate
        pip install pandas pyarrow toml
        pip install "ibis-framework[duckdb]>=10,<11"
        pip install .

    - name: Prepare Snowflake-compatible bundle
      run: |
        . venv/bin/activate
        
        # Get the site-packages directory
        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
        
        # Create a staging directory
        mkdir -p snowflake_staging
        
        # Copy all packages to the staging directory (flattened structure)
        cp -r $SITE_PACKAGES/* snowflake_staging/
        
        # Remove unnecessary files that Snowflake doesn't need
        find snowflake_staging -name "*.pyc" -delete
        find snowflake_staging -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
        find snowflake_staging -name "*.egg-info" -type d -exec rm -rf {} + 2>/dev/null || true
        find snowflake_staging -name "tests" -type d -exec rm -rf {} + 2>/dev/null || true
        
        # Create the zip file from within the staging directory
        cd snowflake_staging
        zip -r ../snowflake_bundle.zip .
        cd ..

    - name: Upload bundle as artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: snowflake-bundle
        path: snowflake_bundle.zip

    - name: Upload bundle to release
      uses: softprops/action-gh-release@v1
      with:
        files: snowflake_bundle.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}