name: Snowflake Bundle

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-snowflake-bundle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Adjust to match Snowflake's supported Python version

    - name: Create virtual environment
      run: python -m venv venv

    - name: Install dependencies in venv
      run: |
        . venv/bin/activate
        pip install pandas pyarrow toml
        pip install "ibis-framework[duckdb]>=10,<11"
        pip install .

    - name: Prepare bundle
      run: |
        . venv/bin/activate
        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
        zip -r snowflake_bundle.zip $SITE_PACKAGES/*

    - name: Upload bundle as artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: snowflake-bundle
        path: snowflake_bundle.zip

    - name: Upload bundle to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./snowflake_bundle.zip
        asset_name: snowflake_bundle.zip
        asset_content_type: application/zip